---
image: quay.io/buildah/stable:v1.34

variables:
  KUBERNETES_MEMORY_REQUEST: "1Gi"
  KUBERNETES_MEMORY_LIMIT: "1Gi"
  REGISTRY_AUTH_FILE: /run/secrets/runner-job-secrets/docker_config_ci.json
  RUNNER_AFTER_SCRIPT_TIMEOUT: 60m

stages:
  - build
  - cicd-pipeline

default:
  # Setup buildah cache for all jobs
  before_script:
    - |
      cat > /etc/containers/registries.conf.d/cache.conf <<EOF
      [[registry]]
      location = "private-registry:5000"
      insecure = true
      EOF
  # Run build in after script to let individual jobs modify environment in the job script. We make use of
  # all builds being identical. The build target is defined by COMPONENT in job variables.
  after_script:
    - cd "${CI_PROJECT_DIR}/container-src/${COMPONENT}"
    - buildah build 
      --storage-driver vfs 
      --jobs 4
      --layers --cache-from private-registry:5000/pebbles/cache --cache-to private-registry:5000/pebbles/cache 
      --tag "${CI_IMAGE_REPO_CI}/${COMPONENT}:${CI_COMMIT_REF_NAME}"
    - buildah push 
      --storage-driver vfs 
      "${CI_IMAGE_REPO_CI}/${COMPONENT}:${CI_COMMIT_REF_NAME}"

build-deployer-image:
  stage: build
  tags: ['new-runner']
  variables:
    COMPONENT: pebbles-deployer
    KUBERNETES_MEMORY_REQUEST: "4Gi"
    KUBERNETES_MEMORY_LIMIT: "4Gi"
  script:
    - echo "building $COMPONENT"

build-backup-image:
  stage: build
  tags: ['new-runner']
  variables:
    COMPONENT: pebbles-backup
  script:
    - echo "building $COMPONENT"

build-logstash-image:
  stage: build
  tags: ['new-runner']
  variables:
    COMPONENT: logstash
  script:
    - echo "building $COMPONENT"

build-filebeat-image:
  stage: build
  tags: ['new-runner']
  variables:
    COMPONENT: filebeat
  script:
    - echo "building $COMPONENT"

build-k3s-autoscaler-image:
  stage: build
  tags: ['new-runner']
  variables:
    COMPONENT: k3s-autoscaler
  script:
    - echo "building $COMPONENT"

# call pipeline project
cicd-pipeline:
  stage: cicd-pipeline
  variables:
    # test using current branch code and image
    PEBBLES_DEPLOY_COMMIT_REF_NAME: "${CI_COMMIT_REF_NAME}"
    PEBBLES_DEPLOY_IMAGE_TAG: "${CI_COMMIT_REF_NAME}"
  trigger:
    project: pebbles/cicd-pipeline
    branch: main
    strategy: depend
