---
image: docker:git

stages:
  - info
  - build
  - ci-pipeline
  - mirroring

info:
  stage: info
  script:
    - echo "On branch $CI_COMMIT_REF_NAME"

build-deployer-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:${CI_COMMIT_REF_NAME} container-src/pebbles-deployer/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:${CI_COMMIT_REF_NAME}
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:${CI_COMMIT_REF_NAME} $CI_DOCKER_REPOSITORY_PUBLIC/pebbles-deployer:${CI_COMMIT_REF_NAME}
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/pebbles-deployer:${CI_COMMIT_REF_NAME}

    # if we are on master branch, push to PUBLISH repo
    - |
      if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:master"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:master $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:master
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:master
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:latest"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:master $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:latest
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:latest
      fi

build-logstash-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:${CI_COMMIT_REF_NAME} container-src/logstash/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/logstash:${CI_COMMIT_REF_NAME}
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:${CI_COMMIT_REF_NAME} $CI_DOCKER_REPOSITORY_PUBLIC/logstash:${CI_COMMIT_REF_NAME}
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/logstash:${CI_COMMIT_REF_NAME}

    # if we are on master branch push to PUBLISH repo
    - |
      if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/logstash:master"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:master $CI_DOCKER_REPOSITORY_PUBLISH/logstash:master
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/logstash:master
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/logstash:latest"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:master $CI_DOCKER_REPOSITORY_PUBLISH/logstash:latest
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/logstash:latest
      fi

build-filebeat-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:${CI_COMMIT_REF_NAME} container-src/filebeat/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:${CI_COMMIT_REF_NAME}
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:${CI_COMMIT_REF_NAME} $CI_DOCKER_REPOSITORY_PUBLIC/filebeat:${CI_COMMIT_REF_NAME}
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/filebeat:${CI_COMMIT_REF_NAME}

    # if we are on master branch push to PUBLISH repo
    - |
      if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:master"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:master $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:master
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:master
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:latest"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:master $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:latest
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:latest
      fi

build-k3s-autoscaler-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/k3s-autoscaler:${CI_COMMIT_REF_NAME} container-src/k3s-autoscaler/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/k3s-autoscaler:${CI_COMMIT_REF_NAME}
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/k3s-autoscaler:${CI_COMMIT_REF_NAME} $CI_DOCKER_REPOSITORY_PUBLIC/k3s-autoscaler:${CI_COMMIT_REF_NAME}
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/k3s-autoscaler:${CI_COMMIT_REF_NAME}

    # if we are on master branch push to PUBLISH repo
    - |
      if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/k3s-autoscaler:master"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/k3s-autoscaler:master $CI_DOCKER_REPOSITORY_PUBLISH/k3s-autoscaler:master
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/k3s-autoscaler:master
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/k3s-autoscaler:latest"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/k3s-autoscaler:master $CI_DOCKER_REPOSITORY_PUBLISH/k3s-autoscaler:latest
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/k3s-autoscaler:latest
      fi

# TODO: we could support testing matching images for pebbles and pebbles-frontend instead of always using master
ci-pipeline:
  stage: ci-pipeline
  needs: [ 'build-deployer-image' ]
  variables:
    ENV_NAME: "${CI_ENV_NAME}"
    DEPROVISION_ENVIRONMENT: 1
    PEBBLES_IMAGE_TAG: master
    PEBBLES_FRONTEND_IMAGE_TAG: master
    PEBBLES_COMMIT_REF_NAME: "${CI_COMMIT_REF_NAME}"
    PEBBLES_ENVIRONMENTS_COMMIT_REF_NAME: "${CI_COMMIT_REF_NAME}"
    PEBBLES_DEPLOY_COMMIT_REF_NAME: "${CI_COMMIT_REF_NAME}"
    ENV_NAME_QA: "${CI_ENV_NAME_QA}"
  trigger:
    project: pebbles/cicd-pipeline
    branch: master
    strategy: depend

mirroring:
  stage: mirroring
  image: python:3.8
  variables:
    GITHUB_MIRROR: git@github.com:CSCfi/pebbles-deploy.git
  script:
    - mkdir mirror_dir
    - cd mirror_dir
    - echo "cloning the gitlab.ci repo"
    - git clone $CI_REPOSITORY_URL pebbles-deploy
    - cd pebbles-deploy
    - echo "pushing to github repo"
    - git checkout master
    - mkdir ~/.ssh
    - echo -e "Host github.com\n    StrictHostKeyChecking no\n" >> ~/.ssh/config
    - eval `ssh-agent -s`
    - ssh-agent bash -c 'ssh-add /root/ssh/pebbles-deploy-key/id_rsa; git push $GITHUB_MIRROR master'
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
