---
image: docker:git

stages:
  - info
  - build
  - ci-pipeline

info:
  stage: info
  script:
    - echo "On branch $CI_COMMIT_REF_NAME"

build-deployer-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:latest container-src/pebbles-deployer/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:latest
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:latest $CI_DOCKER_REPOSITORY_PUBLIC/pebbles-deployer:latest
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/pebbles-deployer:latest

    # if we are on master branch, create latest tags and push to PUBLISH repo
    - |
      if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer as latest"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:latest $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:latest
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/pebbles-deployer:latest
      fi

build-logstash-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:latest container-src/logstash/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/logstash:latest
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:latest $CI_DOCKER_REPOSITORY_PUBLIC/logstash:latest
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/logstash:latest

    # if we are on master branch, create latest tags and push to PUBLISH repo
    - |
      if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/logstash as latest"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:latest $CI_DOCKER_REPOSITORY_PUBLISH/logstash:latest
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/logstash:latest
      fi

build-filebeat-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:latest container-src/filebeat/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:latest
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:latest $CI_DOCKER_REPOSITORY_PUBLIC/filebeat:latest
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/filebeat:latest

    # if we are on master branch, create latest tags and push to PUBLISH repo
    - |
      if [[ ${CI_COMMIT_REF_NAME} == 'master' ]]; then
        echo "Tagging and pushing $CI_DOCKER_REPOSITORY_PUBLISH/filebeat as latest"
        docker tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:latest $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:latest
        docker push $CI_DOCKER_REPOSITORY_PUBLISH/filebeat:latest
      fi

ci-pipeline:
  stage: ci-pipeline
  needs: ['build-deployer-image']
  variables:
    ENV_NAME: pebbles-ci-2
    DEPROVISION_ENVIRONMENT: 1
    PEBBLES_IMAGE_TAG: latest
    PEBBLES_IMAGE_TAG: latest
    PEBBLES_COMMIT_REF_NAME: "${CI_COMMIT_REF_NAME}"
    PEBBLES_ENVIRONMENTS_COMMIT_REF_NAME: "${CI_COMMIT_REF_NAME}"
    PEBBLES_DEPLOY_COMMIT_REF_NAME: "${CI_COMMIT_REF_NAME}"
    ENV_NAME_QA: "${CI_ENV_NAME_QA}"
  trigger:
    project: pebbles/cicd-pipeline
    branch: master
    strategy: depend
