---
image: docker:git

stages:
  - build

build-deployer-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:latest container-src/pebbles-deployer/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:latest
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/pebbles-deployer:latest $CI_DOCKER_REPOSITORY_PUBLIC/pebbles-deployer:latest
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/pebbles-deployer:latest

build-logstash-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:latest container-src/logstash/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/logstash:latest
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/logstash:latest $CI_DOCKER_REPOSITORY_PUBLIC/logstash:latest
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/logstash:latest

build-filebeat-image:
  stage: build
  script:
    - docker build --tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:latest container-src/filebeat/.
    - docker push $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:latest
    - docker tag $CI_DOCKER_REPOSITORY_PRIVATE/filebeat:latest $CI_DOCKER_REPOSITORY_PUBLIC/filebeat:latest
    - docker push $CI_DOCKER_REPOSITORY_PUBLIC/filebeat:latest
