- name: create docker group
  group:
    name: docker
    state: present
  become: True

- name: add ansible user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: True

- name: install yum packages
  yum:
    state: installed
    name:
      - bind-utils
      - git
      - python-devel
      - python-setuptools
      - libffi-devel
      - openssl-devel
      - python-docker-py
  become: True

- name: check out project using git
  git:
    repo: "{{ git_repository }}"
    version: "{{ git_version }}"
    dest: "{{ docker_host_app_root }}"
  become: false
  register: git_status
  when: git_repo_source | default('public_repo') == 'public_repo'

- name: copy local git repo
  synchronize:
    src: /opt/deployment/pebbles/
    dest: /home/cloud-user/pebbles
    rsync_opts:
      - "--exclude=__pycache__"
      - "--exclude=*.pyc"
  when: git_repo_source | default('public_repo') == 'local_directory'

#for some reason the root dir belongs to root anyway
- name: make sure cloud-user owns git
  file:
    setype: svirt_sandbox_file_t
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: true
    path: "{{ docker_host_app_root }}"

# not 100% sure why easy_install and not yum but it's how it was so let's keep
# it
- name: easy_install latest pip
  easy_install:
    name: pip
    state: latest
  become: True

# move over credentials file from localhost, where it should be
- name: ensure in-memory filesystem
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: no
  become: True
  with_items:
    - "{{ application_m2m_credentials_dir }}"
    - /run/shm/
    - /run/

# we could check that local file exists but lack of m2m creds is an error at
# the time of this writing
- name: copy local creds to remote virtual filesystem
  copy:
    src: "{{ local_m2m_credentials_path }}"
    dest: "{{ application_m2m_credentials_path }}"
    owner: root
    group: root
    setype: svirt_sandbox_file_t
    mode: 0644
  become: True

- name: Create ssl dir
  file:
    dest: "{{ docker_host_cert_dir }}"
    owner: root
    group: root
    mode: 0600
    state: directory

- name: check if local key exists
  stat:
    path: "{{ local_ssl_key }}"
  register: stat_local_ssl_key
  become: false
  delegate_to: 127.0.0.1

- name: check if local certificate exists
  stat:
    path: '{{ local_ssl_crt }}'
  register: stat_local_ssl_crt
  become: false
  delegate_to: 127.0.0.1

- name: Create self-signed SSL cert
  command: >
    openssl req -new -nodes -x509
    -subj "/C=FI/ST=SouthernFinland/L=Helsinki/O=IT/CN={{ domain_name }}"
    -days 3650
    -extensions v3_ca
    -keyout {{ docker_host_cert_dir }}/server.key
    -out {{ docker_host_cert_dir }}/server.crt
    creates={{ docker_host_cert_dir }}/server.crt
  register: self_signed_cert
  when: >
    stat_local_ssl_key.stat.exists == False
    or stat_local_ssl_crt.stat.exists == False

- name: Use self-signed SSL cert as a dummy file for chain
  command: cp {{ docker_host_cert_dir }}/server.crt {{ docker_host_cert_dir }}/chain.crt
  when: self_signed_cert is defined and self_signed_cert is changed

- name: Upload fixed certificate
  copy:
    dest: "{{ docker_host_cert_dir }}/server.crt"
    src: "{{ local_ssl_crt }}"
  when: stat_local_ssl_key.stat.exists == True and  stat_local_ssl_crt.stat.exists == True

- name: Upload fixed key
  copy:
    dest: "{{ docker_host_cert_dir }}/server.key"
    src: "{{ local_ssl_key }}"
  when: stat_local_ssl_key.stat.exists == True and  stat_local_ssl_crt.stat.exists == True

- name: create SSO directory
  file:
    dest: "{{ docker_host_sso_dir }}"
    state: directory
  when: use_sso == True

- name: upload SSO files
  copy:
      dest: "{{ docker_host_sso_dir }}/{{item}}"
      src: "{{ sso_cert_local_path }}/{{item}}"
  with_items:
    - sp_key.pem
    - sp_cert.pem
    - idp_cert.pem
  when: use_sso == True

- name: make temporary directory for image build
  tempfile:
    state: directory
    suffix: own
  register: ubuntu_build

- name: prepare docker image source (templates)
  template:
    src: "docker/{{ item }}.j2"
    dest: "{{ ubuntu_build.path }}/{{ item }}"
  with_items:
    - ansible-sudo
    - supervisord.conf
  when: not ansible_check_mode

- name: prepare docker image source (Dockerfile)
  copy:
    src: "Dockerfile"
    dest: "{{ ubuntu_build.path }}/Dockerfile"

- name: prepare docker image source (public key)
  copy:
    src: "/dev/shm/{{ cluster_name }}/id_rsa.pub"
    dest: "{{ ubuntu_build.path }}/id_rsa.pub"
  when: not ansible_check_mode

- name: build image
  docker_image:
    state: present
    source: build
    force_source: yes
    path: "{{ ubuntu_build.path }}"
    name: "{{ docker_image_name }}"
    docker_host: unix:///var/run/docker.sock
  when: not ansible_check_mode

- name: remove temp image build directory
  file: name={{ ubuntu_build.path }} state=absent
  when: not ansible_check_mode

- name: make temporary directory for image build
  tempfile:
    state: directory
    suffix: own
  register: img_build

- name: Pull images
  docker_image:
    name: "{{ item }}"
    state: present
    docker_host: unix:///var/run/docker.sock
  with_items:
    - "{{ docker_image_redis }}"
    - "{{ docker_image_postgres }}"

- name: Allow access to mounted host directories (CentOS)
  file:
    path: "{{ item }}"
    state: directory
    setype: svirt_sandbox_file_t
    recurse: yes
  with_items:
    - "{{ docker_host_app_root }}"
    - "{{ docker_host_image_dir }}"
    - "{{ docker_host_cert_dir }}"
    - "{{ docker_host_m2m_credentials_dir }}"
    - "{{ docker_host_sso_dir }}"
    - "{{ docker_host_database_dir }}"
  when: ansible_lsb.id=="CentOS"

- name: Bring up container for db
  docker_container:
    name: db
    image: "{{ docker_image_postgres }}"
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: "{{ application_database_user }}"
      POSTGRES_PASSWORD: "{{ application_database_password }}"
      #ToDo mount postgres data to an external volume
    volumes:
      - "{{ docker_host_database_dir }}:/var/lib/postgresql/data:rw"

- name: Bring up container for redis
  docker_container:
    name: redis
    image: "{{ docker_image_redis }}"
    state: started
    restart_policy: always

- name: combine common and separate environment variables
  set_fact:
    api_env: "{{ pebbles_environment_config|combine(pebbles_api_config) }}"
    worker_env: "{{ pebbles_environment_config|combine(pebbles_worker_config) }}"
  tags:
    - worker
    - api
    - config

- name: Bring up container for api
  docker_container:
    hostname: api
    image: "{{ docker_image_name }}"
    state: started
    recreate: "{{ recreate_volatile_containers|default('no') }}"
    restart_policy: always
    name: api
    exposed_ports:
      - 22
      - "{{ gunicorn_bind_port }}"
      - "{{ gunicorn_bind_port_worker }}"
    ports:
      - "2222:22"
    links:
      - "db:db"
      - "redis:redis"
    volumes:
      - "{{ docker_host_app_root }}:/shared_folder/source:ro"
      - "{{ provisioning_log_file_root }}"
    env: "{{ api_env }}"
  tags:
    - api
    - config

- name: add api to inventory
  add_host:
    name: api
    groups: docker,api
    ansible_ssh_host: "{{ ansible_host }}"
    ansible_ssh_port: 2222
    ansible_ssh_user: ansible
  tags:
    - api
    - always
  ## see https://github.com/ansible/ansible-modules-core/issues/1005
  # when: item.Config.Hostname == "www" and item.State.Running == True
  # with_items: docker_containers

- name: Bring up container for sso
  docker_container:
    hostname: sso
    image: "{{ docker_image_name }}"
    state: started
    restart_policy: always
    name: sso
    expose:
      - 80
    ports:
      - "2225:22"
    links:
      - "api:api"
    volumes:
      - "{{ docker_host_sso_dir }}:/etc/{{ application_name }}/sso:ro"
  when: enable_shibboleth | bool

- name: add sso to inventory
  add_host:
    name: sso
    groups: docker,sso
    ansible_ssh_host: "{{ ansible_host }}"
    ansible_ssh_port: 2225
    ansible_ssh_user: ansible
  tags:
    - sso
    - always
  when: enable_shibboleth | bool

- name: define frontend links
  set_fact:
    frontend_links: "['api:api', 'redis:redis']"
  when: not enable_shibboleth | bool

- name: define frontend links (shibboleth enabled)
  set_fact:
    frontend_links: "['api:api', 'redis:redis', 'sso:sso']"
  when: enable_shibboleth | bool

- name: Bring up container for frontend
  docker_container:
    hostname: frontend
    image: "{{ docker_image_name }}"
    state: started
    restart_policy: always
    name: frontend
    expose:
      - 22
      - 80
      - "{{ application_external_https_port }}"
    ports:
      - "2224:22"
      - "80:80"
      - "{{ application_external_https_port }}:{{ application_external_https_port }}"
    links: "{{ frontend_links }}"
    volumes:
      - "{{ docker_host_cert_dir }}:/etc/nginx/ssl:ro"
    volumes_from:
      - api:ro
  tags:
    - frontend

- name: add frontend to inventory
  add_host:
    name: frontend
    groups: docker,frontend
    ansible_ssh_host: "{{ ansible_host }}"
    ansible_ssh_port: 2224
    ansible_ssh_user: ansible
  tags:
    - always
    - frontend

- name: Bring up container for worker
  docker_container:
    hostname: worker
    image: "{{ docker_image_name }}"
    state: started
    recreate: "{{ recreate_volatile_containers|default('no') }}"

    restart_policy: always
    name: worker
    expose:
      - 22
    ports:
      - "2223:22"
    links:
      - "api:api"
      - "redis:redis"
    volumes:
      - "{{ docker_host_app_root }}:/shared_folder/source:ro"
      - "{{ docker_host_m2m_credentials_dir }}:{{ application_m2m_credentials_dir }}:ro"
      - "{{ docker_host_image_dir }}:/images:ro"
    env:  "{{ worker_env }}"
  tags:
    - worker
    - config

- name: add worker to inventory
  add_host:
    name: worker
    groups: docker,worker
    ansible_ssh_host: "{{ ansible_host }}"
    ansible_ssh_port: 2223
    ansible_ssh_user: ansible
  tags:
    - worker
    - always

- name: Add aliases to local ssh config
  blockinfile:
    dest:  "{{ ssh_config_file }}"
    backup: yes
    mode: 0700
    create: yes
    block: |
      Host {{ installation_prefix }}{{ item.name }}
          StrictHostKeyChecking no
          User {{ ansible_user }}
          HostName {{ ansible_default_ipv4.address }}
          Port {{ item.port }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{installation_prefix}}{{ item.name }}"
  with_items:
    - { name: api, port: 2222}
    - { name: worker, port: 2223}
    - { name: frontend, port: 2224}
    - { name: sso, port: 2225}
    - { name: docker_host, port: 22}
  become: False
  delegate_to: 127.0.0.1
  tags:
    - always

- name: "Wait a bit for sshd to come up"
  pause: seconds=5
