{{- if and .Values.adminFrontendEnabled (eq .Values.ingressType "Ingress") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-frontend
  labels:
    app: admin-frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  {{- if .Values.ingressClass }}
  ingressClassName: "{{ .Values.ingressClass }}"
  {{- end}}
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        paths:
          - path: /admin
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-frontend
                port:
                  number: 8080

{{- end }}
