{{- if .Values.adminFrontendEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: admin-frontend
  name: admin-frontend
spec:
  ports:
    - name: web 
      port: 8080
      targetPort: 8080
  selector:
    name: admin-frontend
{{- end}}
