{{- if and .Values.adminFrontendEnabled (eq .Values.ingressType "Route") }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: admin-frontend
  {{- if .Values.ipWhitelist }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.ipWhitelist }}
  {{- end }}
spec:
  {{- if .Values.ingressHost }}
  host: {{ .Values.ingressHost }}
  {{- end }}
  path: /admin
  to:
    kind: Service
    name: admin-frontend
    weight: 100
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress: []
{{- end}}
