apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the API pods
  name: api
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    name: api
