apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-api
spec:
  ingress:
  - from:
    - podSelector: {}
  podSelector:
    matchLabels:
      name: api
  policyTypes:
  - Ingress
