apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Pebbles API
  name: api
spec:
  replicas: {{ .Values.apiReplicas }}
  selector:
    matchLabels:
      name: api
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: "api"
        dbAccess: "true"
        logstashAccess: "true"
      name: api
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: "{{ $value}}"
        {{- end }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: {{ .Values.dbImage }}
          imagePullPolicy: {{ .Values.dbImagePullPolicy }}
          command:
            - bash
            - -c
            - |
              until pg_isready; do
                echo "waiting for database $PGHOST:$PGPORT to respond"
                sleep 2
              done
          env:
            - name: PGHOST
              value: "{{ .Values.databaseHost }}"
            - name: PGPORT
              value: "{{ .Values.databasePort }}"
          resources:
            requests:
              cpu: {{ .Values.apiCpuRequest }}
              memory: {{ .Values.apiMemoryRequest }}
            limits:
              cpu: {{ .Values.apiCpuLimit }}
              memory: {{ .Values.apiMemoryLimit }}
      {{- if .Values.apiAutomigrateDb }}
        - name: automigration
          image: {{ .Values.imagePrefix }}{{ .Values.apiImage }}
          imagePullPolicy: {{ .Values.apiImagePullPolicy }}
          env:
            - name: FLASK_APP
              value: {{ .Values.apiFlaskApp }}
            - name: PB_SQLALCHEMY_DATABASE_URI
              value: {{ .Values.databaseUri }}
            - name: PB_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pebbles
                  key: database-password
          command:
            - bash
            - -c
            - |
              echo "Migrating DB to the latest revision"
              flask db upgrade
              echo "Migration done"
          {{- if .Values.mountHostSrc }}
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: src
          {{- end }}
      {{- end }}
      containers:
        - name: api
          env:
            - name: APP_SCRIPT
              value: /opt/app-root/src/deployment/run_gunicorn.bash
            - name: APP_MODULE
              value: {{ .Values.apiFlaskApp }}
            - name: FLASK_APP
              value: {{ .Values.apiFlaskApp }}
            - name: PB_SQLALCHEMY_DATABASE_URI
              value: {{ .Values.databaseUri }}
            - name: PB_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pebbles
                  key: database-password
            {{- if .Values.apiDevelopmentMode }}
            - name: PB_DEBUG
              value: '1'
            - name: GUNICORN_CMD_ARGS
              value: >-
                --access-logfile=/opt/log/access.log
                --access-logformat='%(t)s "%(r)s" %(s)s %(b)s %({x-forwarded-for}i)s "%(f)s" %(M)s'
                --log-file=/opt/log/error.log
                --workers=1
                --reload
                {{- if .Values.apiGunicornReloadEngine }}
                --reload-engine={{ .Values.apiGunicornReloadEngine }}
                {{- end }}
            {{- else }}
            - name: PB_DEBUG
              value: '0'
            - name: GUNICORN_CMD_ARGS
              value: >-
                --access-logfile=/opt/log/access.log
                --access-logformat='%(t)s "%(r)s" %(s)s %(b)s %({x-forwarded-for}i)s "%(f)s" %(M)s'
                --log-file=/opt/log/error.log
                {{ .Values.apiGunicornExtraArgs }}
            {{- end }}
            {{- if .Values.remoteDebugServerApi }}
            - name: REMOTE_DEBUG_SERVER
              value: {{ .Values.remoteDebugServerApi }}
            {{- end }}
            {{- if .Values.apiDisableCORS }}
            - name: DISABLE_CORS
              value: "{{ .Values.apiDisableCORS }}"
            {{- end }}
            - name: PB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pebbles
                  key: pb-secret-key
            {{- if .Values.oauth2LoginEnabled }}
            - name: PB_OAUTH2_LOGIN_ENABLED
              value: '1'
            {{- end }}

          image: {{ .Values.imagePrefix }}{{ .Values.apiImage }}
          imagePullPolicy: {{ .Values.apiImagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.apiCpuRequest }}
              memory: {{ .Values.apiMemoryRequest }}
            limits:
              cpu: {{ .Values.apiCpuLimit }}
              memory: {{ .Values.apiMemoryLimit }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          {{- if .Values.apiPreStopSleepSeconds }}
          lifecycle:
            preStop:
              exec:
                command: ['sleep', '{{ .Values.apiPreStopSleepSeconds }}']
          {{- end }}
          volumeMounts:
            - name: cluster-config
              mountPath: "/run/secrets/pebbles/cluster-config.yaml"
              subPath: cluster-config.yaml
            - name: api-configmap
              mountPath: /run/configmaps/pebbles/api-configmap/
            - mountPath: /opt/log
              name: log
          {{- if .Values.mountHostSrc }}
            - mountPath: /opt/app-root/src
              name: src
          {{- end }}
        {{- if .Values.deployCentralLogging }}
        - name: filebeat
          image: {{ .Values.imagePrefix }}{{ .Values.filebeatImage }}
          imagePullPolicy: {{ .Values.apiImagePullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsGroup: 0
          volumeMounts:
            - mountPath: /opt/log
              name: log
            {{- if .Values.deployCentralLogging }}
            - mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              name: filebeat-config-file
            {{- end }}
        {{- end }}
      volumes:
        - name: cluster-config
          secret:
            secretName: cluster-config
        - name: api-configmap
          configMap:
            name: api-configmap
        - name: log
          emptyDir: {}
      {{- if .Values.mountHostSrc }}
        - name: src
          hostPath:
            path: {{ .Values.mountHostSrc }}
            type: Directory
      {{- end }}
      {{- if .Values.deployCentralLogging }}
        - name: filebeat-config-file
          configMap:
            name: filebeat-config
            items:
              - key: filebeat
                path: filebeat.yml
        {{- end }}
