apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  faq-content.yaml: |
{{- if .Values.faq }}
{{ .Values.faq | indent 4}}
{{- end }}
  auth-config.yaml: |
{{- if .Values.authConfig }}
{{ .Values.authConfig | indent 4}}
{{- end }}
