---
{{- if .Values.backupEnabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backupStorageClass }}
  storageClassName: {{ .Values.backupStorageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.volumeSize }}

{{- end }}
