---
{{- if .Values.backupEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
stringData:
  s3cfg: |
{{ .Values.backup.s3cfg | indent 4 }}

  encrypt-public-key: |
{{ .Values.backup.encryptPublicKey | indent 4 }}

{{- end }}
