---
{{- if .Values.enableBeatsLogging }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: beats-configmap
data:
  logging.yaml: |
    beatsHost: {{ .Values.beatsHost }}
    beatsPort: {{ .Values.beatsPort }}
    loggingExtraFields:
      {{- .Values.loggingExtraFields | toYaml | nindent 6 }}
{{- end }}
