{{- if .Values.bouncerEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bouncer-tls-secret
data:
  {{- if .Values.secretsEncodedByHelm }}
  tls.crt: |
    {{ .Values.bouncerTlsCert | b64enc | indent 4 }}
  tls.key: |
    {{ .Values.bouncerTlsKey | b64enc | indent 4 }}
  {{- else }}
  tls.crt: |
    {{ .Values.bouncerTlsCert | indent 4 }}
  tls.key: |
    {{ .Values.bouncerTlsKey | indent 4 }}
  {{- end }}
{{- end }}
