{{- if .Values.bouncerEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bouncer-tls-secret
data:
  tls.crt: |
{{ .Values.bouncerTlsCert | indent 4 }}

  tls.key: |
{{ .Values.bouncerTlsKey | indent 4 }}

{{- end }}
