{{- if .Values.bouncerEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bouncer-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="Refresh" content="1; URL=https://{{ .Values.bouncerToDomain }}">
        <title>Redirecting to {{ .Values.bouncerToDomain }}</title>
    </head>
    <body>
    Redirecting to
    <a href="https://{{ .Values.bouncerToDomain }}">{{ .Values.bouncerToDomain }}</a>
    </body>
    </html>

  redirect_to_index.conf: |
    error_page 404 /index.html;

  # adapted from bitnami nginx example
  bouncer_server_block.conf: |
    server {
        listen       8443 ssl;

        ssl_certificate      /opt/bitnami/nginx/certs/tls.crt;
        ssl_certificate_key  /opt/bitnami/nginx/certs/tls.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
          root   html;
          index  index.html;
        }
    }

{{- end }}
