{{- if .Values.bouncerEnabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bouncer
  {{- if .Values.ipWhitelist }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.ipWhitelist }}
  {{- end }}
spec:
  {{- if .Values.bouncerFromDomain }}
  host: {{ .Values.bouncerFromDomain }}
  {{- end }}
  to:
    kind: Service
    name: bouncer
    weight: 100
  port:
    targetPort: web-secure
  tls:
    insecureEdgeTerminationPolicy: Redirect
    {{- if .Values.bouncerTlsCert }}
    termination: passthrough
    {{- else }}
    termination: edge
    {{- end }}
status:
  ingress: [ ]

{{- end }}
