{{- if .Values.dbDeploymentEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-db
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          dbAccess: "true"
  podSelector:
    matchLabels:
      name: db
  policyTypes:
  - Ingress
{{- end }}
