---
{{- if .Values.databaseVolumeSize }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.dbStorageClass }}
  storageClassName: {{ .Values.dbStorageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.databaseVolumeSize }}

{{- end }}
