{{- if .Values.networkPolicyDefaultIngressNamespaces }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-policy
spec:
  ingress:
  - from:
      {{- range .Values.networkPolicyDefaultIngressNamespaces }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ . }}
      {{- end }}
  policyTypes:
  - Ingress
  podSelector: {}
{{- end }}