{{- if eq .Values.ingressType "Route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
spec:
  {{- if .Values.ingressHost }}
  host: {{ .Values.ingressHost }}
  {{- end }}
  to:
    kind: Service
    name: frontend
    weight: 100
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress: []
{{- end}}
