apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: frontend
  name: frontend
spec:
  ports:
    - name: web 
      port: 8080
      targetPort: 8080
  selector:
    name: frontend
