apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontendReplicas }}
  selector:
    matchLabels:
      name: frontend
  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        name: frontend
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: "{{ $value}}"
        {{- end }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.imagePrefix }}{{ .Values.frontendImage }}
          imagePullPolicy: {{ .Values.frontendImagePullPolicy }}
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.frontendCpuRequest }}
              memory: {{ .Values.frontendMemoryRequest }}
            limits:
              cpu: {{ .Values.frontendCpuLimit }}
              memory: {{ .Values.frontendMemoryLimit }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
