apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        name: frontend
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: "{{ $value}}"
        {{- end }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.imagePrefix }}{{ .Values.frontendImage }}
          imagePullPolicy: {{ .Values.frontendImagePullPolicy }}
          ports:
          - containerPort: 8080
