---
{{- if .Values.maintenanceCronJobEnabled }}
apiVersion: {{ .Values.batchJobApiVersion }}
kind: CronJob
metadata:
  name: maintenance
spec:
  schedule: "{{ .Values.maintenanceCronJobSchedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: maintenance
              image: {{ .Values.imagePrefix }}{{ .Values.apiImage }}
              imagePullPolicy: Always
              command: [ "python", "pebbles/maintenance/main.py" ]
              args: {{ .Values.maintenanceCronJobArgs | toJson }}
              env:
                - name: PB_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: pebbles
                      key: pb-secret-key
                - name: PYTHONPATH
                  value: /opt/app-root/src
                {{- if .Values.enableBeatsLogging }}
                - name: PB_BEATS_LOGGING_CONFIG_FILE_PATH
                  value: "{{ .Values.beatsLoggingConfigFilePath }}"
                - name: PB_ENABLE_BEATS_LOGGING
                  value: "{{ .Values.enableBeatsLogging }}"
                - name: PB_BEATS_HOST
                  value: "{{ .Values.beatsHost }}"
                - name: PB_BEATS_PORT
                  value: "{{ .Values.beatsPort }}"
                {{- end }}
              volumeMounts:
                - name: beats-configmap
                  mountPath: run/configmaps/pebbles/beats-configmap
          volumes:
            - name: beats-configmap
              configMap:
                name: beats-configmap
{{- end }}
