{{- if and .Values.oauth2LoginEnabled (eq .Values.ingressType "Ingress")  }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- if .Values.ingressClass }}
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    {{- end}}
spec:
  rules:
    - host: {{ .Values.ingressHost | default "localhost" }}
      http:
        paths:
          - path: /oauth2
            pathType: ImplementationSpecific
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80

{{- end }}
