{{- if and .Values.oauth2LoginEnabled (eq .Values.ingressType "Route") }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: oauth2-proxy
spec:
  host: {{ .Values.ingressHost }}
  path: /oauth2
  to:
    kind: Service
    name: oauth2-proxy
    weight: 100
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status:
  ingress: []
{{- end}}
