{{- if .Values.oauth2LoginEnabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
stringData:
  client-id: {{ .Values.oauth2ProxyClientId | quote }}
  client-secret: {{ .Values.oauth2ProxyClientSecret | quote }}
  cookie-secret: {{ .Values.oauth2ProxyCookieSecret | default (randAlphaNum 32) | quote }}
  cookie-expire: {{ .Values.oauth2ProxyCookieExpire | default ("1m") }}

{{- end }}
