{{- if .Values.oauth2LoginEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: oauth2-proxy

{{- end }}
