{{- if .Values.overrideSecret | default false }}
# to avoid regenerating secrets during upgrades, only create it when explicitly asked for
---
apiVersion: v1
kind: Secret
metadata:
  name: pebbles
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
stringData:
  database-user: pebbles
  database-password: {{ .Values.databasePassword | default (randAlphaNum 16) | quote }}
  pb-secret-key: {{ .Values.pbSecretKey | default (randAlphaNum 32) | quote }}
{{- end }}
