# to avoid regenerating secrets during upgrades, only create it if it does not exist
{{- if not (lookup "v1" "Secret" .Release.Namespace "pebbles") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: pebbles
  annotations:
    helm.sh/resource-policy: keep
stringData:
  database-user: pebbles
  database-password: {{ .Values.databasePassword | default (randAlphaNum 16) | quote }}
  pb-secret-key: {{ .Values.pbSecretKey | default (randAlphaNum 32) | quote }}
{{- end }}
