apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  serviceName: worker
  selector:
    matchLabels:
      name: worker
  replicas: {{ .Values.workerReplicas }}
  template:
    metadata:
      labels:
        name: worker
        logstashAccess: "true"
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: "{{ $value}}"
        {{- end }}
      {{- end }}
      serviceAccountName: worker
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: wait-for-api
          image: {{ .Values.imagePrefix }}{{ .Values.workerImage }}
          imagePullPolicy: {{ .Values.workerImagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.workerCpuRequest }}
              memory: {{ .Values.workerMemoryRequest }}
            limits:
              cpu: {{ .Values.workerCpuLimit }}
              memory: {{ .Values.workerMemoryLimit }}
          command:
            - bash
            - -c
            - until curl -s -m 1 -o /dev/null api:8080/api/v1/config; do echo waiting for api; sleep 1; done
        {{- if .Values.useSourceVolume }}
        - name: init-source-volume
          image: {{ .Values.imagePrefix }}{{ .Values.workerImage }}
          imagePullPolicy: {{ .Values.workerImagePullPolicy }}
          command:
            - bash
            - -c
            - if [[ ! -d /mnt/source-volume/pebbles ]]; then rsync -avi /opt/app-root/src/* /mnt/source-volume/.; fi
          volumeMounts:
            - name: src
              mountPath: /mnt/source-volume

        {{- end }}
      containers:
        - name: worker
          image: {{ .Values.imagePrefix }}{{ .Values.workerImage }}
          imagePullPolicy: {{ .Values.workerImagePullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.workerCpuRequest }}
              memory: {{ .Values.workerMemoryRequest }}
            limits:
              cpu: {{ .Values.workerCpuLimit }}
              memory: {{ .Values.workerMemoryLimit }}
          command:
            - python
            - pebbles/worker/main.py
          env:
            - name: PYTHONPATH
              value: /opt/app-root/src
            - name: PB_INTERNAL_API_BASE_URL
              value: http://api:8080/api/v1
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PB_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: pebbles
                  key: pb-secret-key
            - name: PB_ENABLE_FILE_LOGGING
              value: '1'
            {{- if .Values.remoteDebugServerWorker }}
            - name: REMOTE_DEBUG_SERVER
              value: {{ .Values.remoteDebugServerWorker }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: worker-configmap
          volumeMounts:
            - name: cluster-config
              mountPath: "/run/secrets/pebbles/cluster-config.yaml"
              subPath: cluster-config.yaml
            - name: cluster-passwords
              mountPath: "/run/secrets/pebbles/cluster-passwords.yaml"
              subPath: cluster-passwords.yaml
            - name: cluster-kubeconfig
              mountPath: "/run/secrets/pebbles/cluster-kubeconfig"
              subPath: cluster-kubeconfig
            - name: log
              mountPath: /opt/log
          {{- if .Values.backupEnabled }}
            - name: backup-secret
              mountPath: "/run/secrets/pebbles/backup-secret"
          {{- end }}
          {{- if or .Values.mountHostSrc .Values.useSourceVolume }}
            - name: src
              mountPath: /opt/app-root/src
          {{- end }}
        {{- if .Values.deployCentralLogging }}
        - name: filebeat
          image: {{ .Values.imagePrefix }}{{ .Values.filebeatImage }}
          imagePullPolicy: {{ .Values.workerImagePullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 100m
              memory: 150Mi
          securityContext:
            runAsGroup: 0
          volumeMounts:
            - mountPath: /opt/log
              name: log
            {{- if .Values.deployCentralLogging }}
            - mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              name: filebeat-config-file
            {{- end }}
        {{- end }}
      volumes:
        - name: cluster-config
          secret:
            secretName: cluster-config
        - name: cluster-passwords
          secret:
            secretName: cluster-passwords
        - name: cluster-kubeconfig
          secret:
            secretName: cluster-kubeconfig
        - name: worker-secret
          secret:
            secretName: worker-secret
        - name: log
          emptyDir: {}
        {{- if .Values.deployCentralLogging }}
        - name: filebeat-config-file
          configMap:
            name: filebeat-config
            items:
              - key: filebeat
                path: filebeat.yml
        {{- end }}
      {{- if .Values.backupEnabled }}
        - name: backup-secret
          secret:
            secretName: backup-secret
      {{- end }}
      {{- if .Values.mountHostSrc }}
        - name: src
          hostPath:
            path: {{ .Values.mountHostSrc }}
            type: Directory
      {{- end }}
      {{- if .Values.useSourceVolume }}
        - name: src
          persistentVolumeClaim:
            claimName: source
      {{- end }}
