# https://github.com/kubernetes/kubernetes/issues/69608
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: A placeholder service for worker statefulset
  name: worker
spec:
  clusterIP: None
  selector:
    name: worker
