apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-edit-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: worker
