---
heat_template_version: 2015-10-15

description: >
  Cinder volumes for Pebbles persistence.

parameters:
  env_name:
    description: >
      environment name, used for labels
    type: string
  k3slib_vol_size:
    description: >
      Size of k3slib volume
    type: string
    default: '120'
  backup_vol_size:
    description: >
      Size of (database) backup volume
    type: string
    default: '50'
  images_vol_size:
    description: >
      Size of image store volume
    type: string
    default: '200'
  nfs_vol_size:
    description: >
      Size of image store volume
    type: string
    default: '10'

resources:
    k3slib_volume:
      type: OS::Cinder::Volume
      properties:
        name:
          list_join: ['-', [{ get_param: env_name }, 'k3slib']]
        size: { get_param: k3slib_vol_size }
    backup_volume:
      type: OS::Cinder::Volume
      properties:
        name:
         list_join: ['-', [{ get_param: env_name }, 'backup']]
        size: { get_param: backup_vol_size }
    images_volume:
      type: OS::Cinder::Volume
      properties:
        name:
          list_join: ['-', [{ get_param: env_name }, 'images']]
        size: { get_param: images_vol_size }
    nfs_volume:
      type: OS::Cinder::Volume
      properties:
        name:
          list_join: ['-', [{ get_param: env_name }, 'nfs']]
        size: { get_param: nfs_vol_size }
