---
- name: Provision storage
  hosts: localhost
  connection: local
  vars:
    network_name: "{{ cluster_name }}-network"
    k3s_api_internal_ip: "{{ network_prefix }}.11"
    k3s_api_public_ip: "{{ master_public_ip }}"
    network: "{{ cluster_name }}-network"
    key_name: "{{ cluster_name }}"
    num_storage_vms: 3
    fcos_max_user_namespaces: 65536
  tasks:
    - include_role:
        name: k3s_vm
      vars:
        vm_role: storage
        server_name: "{{ item }}"
        server_ip: "{{ hostvars[item].ansible_ssh_host }}"
        image: "{{ storage_vm_image }}"
        flavor: "{{ storage_vm_flavor }}"
        volume_size: "{{ storage_volume_size }}"
        wait_for_server: "{{ ansible_loop.last }}"
        server_group: "{{ cluster_name }}-infra"
        security_groups:
          - "{{ cluster_name}}-common"
          - "{{ cluster_name}}-infra"
          - "{{ cluster_name}}-storage"
          - "{{ cluster_name}}-node"
        lock_server: "{{ lock_servers | d(false) }}"
      loop: "{{ groups.storage | default([]) }}"
      loop_control:
        extended: true

- import_playbook: generate_ssh_config.yml
