- name: Create ansible config directory
  file:
    name: /etc/ansible
    state: directory

- name: Setup ansible config
  template:
    src: etc/ansible/ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    backup: yes

- name: Create .docker
  file:
    name: /home/{{ application_user }}/.docker
    state: directory

- name: Setup default CA cert in .docker
  file:
    name: /home/{{ application_user }}/.docker/ca.pem
    src: "{{ docker_cert_dir }}/ca_cert.pem"
    state: link

- name: Setup default client key in .docker
  file:
    name: /home/{{ application_user }}/.docker/key.pem
    src: "{{ docker_cert_dir }}/client_key.pem"
    state: link

- name: Setup default client cert in .docker
  file:
    name: /home/{{ application_user }}/.docker/cert.pem
    src: "{{ docker_cert_dir }}/client_cert.pem"
    state: link

- name: Create images directory
  file:
    name: /images
    state: directory

- name: Make a base directory for state files of the provisioned instances
  file:
    name: "{{ instance_data_dir }}"
    state: directory
    owner: "{{ application_user }}"
