- name: Generate CA key and certificate
  command:
    cmd: >
      openssl req -new -nodes -x509 -subj "/C=FI/ST=SouthernFinland/L=Helsinki/O=IT/CN={{ domain_name }}" -days 3650
      -keyout {{ docker_cert_dir }}/ca_key.pem
      -out {{ docker_cert_dir }}/ca_cert.pem
    creates: "{{ docker_cert_dir }}/ca_cert.pem"

- name: Generate client key and certificate request
  command:
    cmd: >
      openssl req -new -nodes -subj '/CN=client'
      -keyout {{ docker_cert_dir }}/client_key.pem
      -out {{ docker_cert_dir }}/client.csr
    creates: "{{ docker_cert_dir }}/client_key.pem"

- name: Generate signing config
  lineinfile:
    dest: "{{ docker_cert_dir }}/extfile.cnf"
    line: "extendedKeyUsage = clientAuth"
    create: yes

- name: Sign client certificate
  command:
    cmd: >
      openssl x509 -req -days 3650 -CAcreateserial
      -in {{ docker_cert_dir }}/client.csr
      -CA {{ docker_cert_dir }}/ca_cert.pem
      -CAkey {{ docker_cert_dir }}/ca_key.pem
      -out {{ docker_cert_dir }}/client_cert.pem
      -extfile {{ docker_cert_dir }}/extfile.cnf
    creates: "{{ docker_cert_dir }}/client_cert.pem"

- name: Generate a self signed certificate for docker servers
  command:
    cmd: >
      openssl req -new -nodes  -subj '/CN=server'
      -keyout {{ docker_cert_dir }}/server_key.pem
      -out {{ docker_cert_dir }}/server.csr
    creates: "{{ docker_cert_dir }}/server_key.pem"

- name: Sign server certificate
  command:
    cmd:
      openssl x509 -req -days 3650 -CAcreateserial
      -in {{ docker_cert_dir }}/server.csr
      -CA {{ docker_cert_dir }}/ca_cert.pem
      -CAkey {{ docker_cert_dir }}/ca_key.pem
      -out {{ docker_cert_dir }}/server_cert.pem
    creates: "{{ docker_cert_dir }}/server_cert.pem"

- name: Change ownership and fix permissions of certificates and keys
  file:
    name: "{{ docker_cert_dir }}/{{ item }}"
    owner: "{{ application_user }}"
    mode: "u=r"
  with_items:
    - ca_cert.pem
    - ca_key.pem
    - client_cert.pem
    - client_key.pem
    - server_cert.pem
    - server_key.pem
