---

- name: Fetch application from Github
  git: repo={{ git_repository }} version={{ git_version }} dest={{ application_path }}
  when: deploy_mode == "standalone"

- name: Link shared directory content to application_path from Docker shared directory
  file:
    dest: "{{ application_path }}"
    src: "{{ shared_folder_path }}/source"
    state: link
  when: deploy_mode == "docker"

# TODO: unify this with docker deployment
- name: Link shared directory content to application_path
  file: src={{ shared_folder_path }} dest={{ application_path }} state=link
  when: deploy_mode == "devel"

# there's something fishy about installing Sphinx at the same time as building
# a lot of things that use it: the packages sphinx uses aren't isntalled
# correctly. Hence install Sphinx first.
#- name: Install latest version of Sphinx
#  pip: name=Sphinx state=latest virtualenv={{ virtualenv_path }}

- name: Install latest version of separately installable software
  pip:
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    name:
      - pbr
      - pyopenssl
      - pyasn1
      - ndg-httpsclient
      - "requests[security]"

- name: Install dependencies from requirements.txt
  pip:
    requirements: "{{ application_path }}/requirements.txt"
    virtualenv: "{{ virtualenv_path }}"
  environment:
      LC_ALL: C.UTF-8
