- name: Tools for debugging installation
  yum:
    state: present
    name:
      - dstat
      - lsof
      - bash-completion
      - time
  when: ansible_lsb.id=="CentOS"

- name: Install dependencies
  yum:
    state: present
    name:
      - git
      - python
      - python-pip
      - python-dev
      - libffi-devel
      - openssl-devel
      - python-virtualenv
      - supervisor
  when: ansible_lsb.id=="CentOS"

#- name: Install Python SSL libs to avoid issues with SNI and old python
#  pip:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - pyopenssl
#    - ndg-httpsclient
#    - pyasn1

- include: create_users_and_groups.yml
- include: setup_virtualenv.yml
- include: fetch_application.yml
- include: setup_supervisor.yml
- include: setup_runtime_directories.yml
