apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: logstash
  name: logstash
spec:
  output:
    to:
      kind: ImageStreamTag
      name: logstash:latest
  source:
    binary: {}
    contextDir: container-src/logstash
  strategy:
    type: Docker
