apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: pebbles-frontend
  name: pebbles-frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pebbles-frontend:latest
  source:
    git:
      uri: https://github.com/CSCfi/pebbles-frontend/
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: deployment/Dockerfile.multi-stage
