apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: pebbles
  name: pebbles
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pebbles:latest
  source:
    git:
      uri: https://github.com/CSCfi/pebbles/
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: deployment/pebbles.Dockerfile
      buildArgs:
      - name: APP_VERSION
        value: "unknown"
