apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: pebbles-frontend
  name: pebbles-frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pebbles-frontend:latest
  source:
    git:
      uri: https://github.com/CSCfi/pebbles-frontend/
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: deployment/Dockerfile.multi-stage
      buildArgs:
      - name: APP_VERSION
        value: "unknown"
  resources:
    limits:
      memory: 4Gi
      cpu: 2
    requests:
      cpu: 1
      memory: 1Gi
