apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: pebbles-backup
  name: pebbles-backup
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pebbles-backup:latest
  source:
    binary: {}
    contextDir: container-src/pebbles-backup
  strategy:
    type: Docker
