apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: pebbles
  name: pebbles
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pebbles:latest
  source:
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: deployment/pebbles.Dockerfile
      buildArgs:
      - name: PB_APP_VERSION
        value: "unknown"
      - name: EXTRA_PIP_PACKAGES
        value: ""
  resources:
    limits:
      cpu: 1
    requests:
      cpu: 1
