apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: pebbles
  name: pebbles
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pebbles:latest
  source:
    git:
      uri: https://github.com/CSCfi/pebbles/
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: centos/python-36-centos7:latest
    type: Source
