---
# disassociate volumes
# disassociate ips
# remove the stack created in provision_heat.yml

- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - pebbles_facts
  tasks:
    - name: Disassociate floating IP from bastion
      os_floating_ip:
        server: "{{ cluster_name }}-jump"
        floating_ip_address: "{{ jump_host_public_ip }}"
        state: absent
    - name: Disassociate floating IP from pebbles node
      os_floating_ip:
        server: "{{ cluster_name }}-server"
        floating_ip_address: "{{ pebbles_public_ip }}"
        state: absent
    - name: disassociate volumes with server node
      os_server_volume:
          server: "{{ cluster_name}}-server"
          state: absent
          volume: "{{ item }}"
      with_items:
          - "{{ cluster_name }}-docker"
          - "{{ cluster_name }}-backup"
          - "{{ cluster_name }}-images"
    - name: Delete public key
      os_keypair:
        state: absent
        name: "{{ cluster_name }}"
    - name: Delete stack {{ cluster_name }}
      os_stack:
        name: "{{ cluster_name }}"
        state: absent
        wait: yes
