---
- hosts: masters
  gather_facts: no
  tasks:
    - name: copy kubeconfig to deployment container (a failure will be ignored)
      fetch:
        src: /home/cloud-user/.kube/config
        dest: /opt/deployment/.kube/config
        flat: yes
      run_once: true
      failed_when: false
