---
- name: Create temporary files on a RAM disk for TLS certs, ssh keys, OpenStack credentials
  hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - pebbles_facts
    - pebbles_deployer
  tasks:

    - when: openshift_username is defined
      block:
        - name: Login to remote OpenShift using robot credentials
          k8s_auth:
            host: "{{ openshift_host }}"
            username: "{{ openshift_username }}"
            password: "{{ openshift_password }}"
          register: k8s_auth_results

        - set_fact:
            k8s_auth: "{{ k8s_auth_results.k8s_auth }}"
          when: openshift_username is defined

        - name: Create .kube directory
          file:
            path: /opt/deployment/.kube
            state: directory
            mode: '0700'

        - name: Create .kube/config
          template:
            src: kube_config.yaml.j2
            dest: /opt/deployment/.kube/config
    # end block

    - when: deployment_type in ('helm', 'k3s')
      block:
        - name: Create values.yaml for Helm (config)
          blockinfile:
            path: '/dev/shm/{{ cluster_name }}/values.yaml'
            create: yes
            mode: '0600'
            marker: "# {mark} Ansible generated values"
            block: "{{ helm_config }}"
          when: helm_config is defined

        - name: Create values.yaml for Helm (cluster passwords)
          blockinfile:
            path: '/dev/shm/{{ cluster_name }}/values.yaml'
            create: yes
            mode: '0600'
            marker: "# {mark} Ansible generated cluster passwords"
            block: "{{ helm_cluster_passwords }}"
          when: helm_cluster_passwords is defined

        - name: Create values.yaml for Helm (cluster kubeconfig)
          blockinfile:
            path: '/dev/shm/{{ cluster_name }}/values.yaml'
            create: yes
            mode: '0600'
            marker: "# {mark} Ansible generated cluster kubeconfig"
            block: "{{ helm_cluster_kubeconfig }}"
          when: helm_cluster_kubeconfig is defined

    # end block
