- hosts: masters, nodes
  gather_facts: yes
  become: yes
  tasks:
    - when: private_registry_enabled | default(false) | bool
      block:
        - name: create directory for k3s registry config
          file:
            path: /etc/rancher/k3s
            state: directory
      
        - name: set up mirror for local registry
          copy:
            dest: /etc/rancher/k3s/registries.yaml
            content: |
              mirrors:
                "private-registry:5000":
                  endpoint:
                    - "http://{{ hostvars[groups['masters'][0]].ansible_ssh_host }}:5000"
          register: k3s_file

- hosts: masters
  gather_facts: yes
  become: yes
  tasks:
    - name: restart k3s service
      systemd:
        name: k3s-master
        state: restarted
      when:
        - private_registry_enabled | default(false) | bool
        - k3s_file.changed

- hosts: nodes
  gather_facts: yes
  become: yes
  tasks:
    - name: restart k3s service
      systemd:
        name: k3s-agent
        state: restarted
      when:
        - private_registry_enabled | default(false) | bool
        - k3s_file.changed
