---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - include: environment_context.yml
    - name: set the name of the volume stack
      set_fact:
        stack_name: "{{ cluster_name }}-volumes"
    - name: check if stack has been provisioned already
      shell: openstack stack show {{ stack_name }}
      register: stack_output
      failed_when: false
      changed_when: false
    - block:
      - name: Build the stack of drives
        register: heat_volumes
        os_stack:
          name: "{{ stack_name }}"
          state: present
          template: "files/pebbles-heat-volume-stack.yml"
          wait: yes
          parameters:
            env_name: "{{ cluster_name }}"
            docker_vol_size: "{{ docker_vol_size|default(100) }}"
            backup_vol_size: "{{ backup_vol_size|default(20) }}"
            images_vol_size: "{{ images_vol_size|default(200) }}"
      when:
        - permanent_volumes
        - stack_output.stderr.find('Stack not found') != -1