---
- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - pebbles_facts
  tasks:
    - name: Add public key to OpenStack for {{ cluster_name }}
      os_keypair:
        state: present
        name: "{{ cluster_name }}"
        public_key_file: "/dev/shm/{{ cluster_name }}/id_rsa.pub"

    - name: check if stack has been provisioned already
      shell: openstack stack show {{ cluster_name }}
      register: stack_output
      failed_when: false
      changed_when: false

    - when:
        - stack_output.stderr.find('Stack not found') != -1 or force_heat_stack_update | d() | bool
      block:
        - name: Build the Pebbles Heat stack
          register: heat_stack
          os_stack:
            name: "{{ cluster_name }}"
            state: present
            template: "files/pebbles-heat-stack.yml"
            wait: yes
            parameters:
              env_name: "{{ cluster_name }}"
              jump_host_allow_ports: "{{ jump_host_allow_ports }}"
              jump_host_allow_cidrs: "{{ jump_host_allow_cidrs }}"
              pebbles_network_dns_servers: "{{ pebbles_network_dns_servers }}"
              pebbles_allow_cidrs: "{{ pebbles_allow_cidrs }}"
              pebbles_allow_ports: "{{ pebbles_allow_ports }}"
              secgroup_ext_access_rules: "{{ secgroup_ext_access_rules }}"
              pebbles_network_cidr: "{{ pebbles_network_cidr }}"
              pebbles_router: "{{ pebbles_router }}"
              key_name: "{{ cluster_name }}"
              jump_host_vm_image: "{{ jump_host_vm_image }}"
              jump_host_vm_flavor: "{{ jump_host_vm_flavor }}"
              jump_host_vm_ip: "{{ pebbles_network_prefix }}.10"
              jump_host_cloud_config: "{{ jump_host_cloud_config|default({}) }}"
              pebbles_vm_image: "{{ pebbles_vm_image }}"
              pebbles_vm_flavor: "{{ pebbles_vm_flavor }}"
              pebbles_vm_ip: "{{ pebbles_network_prefix }}.11"

        - name: Associate fixed floating IP with server node
          os_floating_ip:
            server: "{{ cluster_name }}-server"
            floating_ip_address: "{{ pebbles_public_ip }}"

        - name: Associate fixed floating IP with first jump host
          os_floating_ip:
            server: "{{ cluster_name }}-jump"
            floating_ip_address: "{{ jump_host_public_ip }}"
          when: jump_host_public_ip is defined

        - name: Associate volumes with server node
          os_server_volume:
            server: "{{ cluster_name}}-server"
            state: present
            volume: "{{ item }}"
          with_items:
            - "{{ cluster_name }}-docker"
            - "{{ cluster_name }}-backup"
            - "{{ cluster_name }}-images"
          when:
            - permanent_volumes

      # endblock

- include: generate_ssh_config.yml

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Wait for connectivity on port 22 on the jump_host
      wait_for:
        host: "{{ jump_host_public_ip }}"
        port: 22
        search_regex: "OpenSSH"
        delay: 5
        timeout: 900

    - name: Wait for SSH to work
      shell: >
        ssh {{ jump_host_public_ip }}
        'echo success'
      register: result
      until: result.stdout.find('success') != -1
      retries: 30
      delay: 5
      changed_when: false

- name: Install nmap-ncat on bastion if need be
  hosts: jump_host
  gather_facts: no
  become: yes
  tasks:
    - name: Install nmap-ncat
      yum:
        name: nmap-ncat
        state: present
